-- #281 follow-up (PR review finding): the sub-millisecond half of the
-- conversation-list cursor bug.
--
-- conversations.updated_at is the list cursor's sort key, and every read of
-- it goes through a JS Date, which cannot represent anything finer than a
-- millisecond. The column was plain timestamptz (microsecond), and
-- createConversation inserts without an explicit value -- so a row took
-- defaultNow()'s real microsecond timestamp and kept it until that
-- conversation's first message or rename.
--
-- A cursor built from such a row was therefore truncated on the way out:
-- stored .000615, compared as .000. The compound (updated_at, id) cursor
-- added earlier in #281 cannot rescue that -- the truncated value is
-- neither strictly less than NOR equal to the stored one, so a sibling
-- inside the same millisecond matched no branch of the comparison and was
-- dropped from BOTH pages. That is the exact defect #281 was filed about,
-- surviving underneath its own fix.
--
-- Narrowing the column to millisecond makes Postgres store what the rest of
-- the stack already assumes, so the round-trip is lossless. No writer
-- changes: $onUpdate and appendMessage already write millisecond JS Dates;
-- only defaultNow() was ever finer.
--
-- This is a column rewrite, not a backfill script -- Postgres re-writes
-- existing values as part of the type change, rounding each to the nearest
-- millisecond.
--
-- #429: NOT "the value the application has always read", as this comment
-- previously claimed. Postgres ROUNDS to timestamp(3); the JS Date round-trip
-- TRUNCATED. A row stored ...:00.000615 was read by the app as .000 and is
-- rewritten here as .001. Roughly half of all existing rows therefore move
-- FORWARD by up to 1ms rather than staying put.
--
-- The consequence is narrow and one-deploy-only, but real: a client holding a
-- nextCursor derived from a truncated value across this deploy asks for
-- (updated_at, id) < (T, id). A sibling that was T.000615 -- previously equal
-- to T, so it matched the eq(updated_at) AND lt(id) branch and belonged on
-- page 2 -- is now T+1ms, strictly greater than the cursor, and is skipped on
-- page 2 having never appeared on page 1. It reappears on the client's next
-- refetch from the top.
--
-- Recorded rather than fixed: the migration has already run, and the rounding
-- direction must not be relied on by anything written later. Two rows that
-- round to the SAME millisecond become a genuine tie, which the
-- (updated_at, id) tiebreaker already handles.
ALTER TABLE "conversations" ALTER COLUMN "updated_at" SET DATA TYPE timestamp (3) with time zone;
