config:
  aws:region: us-west-2
  llteacher-infra:environment: production
  # Select domainName, apply, delegate the zone, then set domainReady: "true".
  llteacher-infra:imageTag: bootstrap
  llteacher-infra:provisionService: "false"
  llteacher-infra:deployApp: "false"
