config:
  aws:region: us-west-2
  llteacher-infra:environment: production
  llteacher-infra:domainName: llteacher.org
  llteacher-infra:hostedZoneId: Z04949392GJA8YXNAE52T
  llteacher-infra:certificateArn: arn:aws:acm:us-west-2:055237683908:certificate/abcfe27a-3c24-4c81-9546-654720a9a108
  llteacher-infra:domainReady: "true"
  llteacher-infra:imageTag: bootstrap
  llteacher-infra:provisionService: "false"
  llteacher-infra:deployApp: "false"
secretsprovider: awskms://alias/llteacher-pulumi-state?region=us-west-2&awssdk=v2
encryptedkey: AQICAHgVZtY7d8yTF3BQokXOCXwVUTYGvARbo2UJgd+LVESO2wGyUS/cvQUfWCMVn/SJIaSLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9XXCLuU36wJ/knG3AgEQgDvCSn6rrBjaiynIWcPK7VwripAy4Oyhz8tKpkwAZpreOjEW9kbRnrUoASb4pk81eTzaP0Z9hkXbyWqc1A==
