config:
  aws:region: us-east-1
  llteacher-infra:environment: production
  llteacher-infra:domainName: llteacher.com
  # Set with: pulumi config set hostedZoneId <route53-zone-id> --stack production
  llteacher-infra:imageTag: latest
