/* Generative-UI components — rendered inline inside AI messages when the
   LLM invokes a structured-output tool. */

export { DefinitionCard } from "./DefinitionCard";
export type { DefinitionCardProps } from "./DefinitionCard";
export { renderToolPart, parseShowDefinitionInput, parseExecuteRCodeInput, isToolPart } from "./render";
export { RENDERABLE_TOOL_NAMES, isRenderableToolPartType } from "./renderableTools";
export type { ToolPart, ToolPartHandlers } from "./render";
export { CodeExecution, renderTextWithCode, splitRCodeSegments } from "./renderers/CodeExecution";
export type { CodeExecutionProps, RCodeResult, RenderTextWithCodeOptions, RCodeSegment } from "./renderers/CodeExecution";
export { SectionCompleteSuggestion } from "./renderers/SectionCompleteSuggestion";
export type { SectionCompleteSuggestionProps } from "./renderers/SectionCompleteSuggestion";
export { FIGURE_TOOL_PART_TYPES } from "./render";
export { ToolPartErrorBoundary } from "./ToolPartErrorBoundary";
export { FigurePlate } from "./figure/FigurePlate";
export { WorkedSteps } from "./renderers/WorkedSteps";
export { MacroModelDiagram } from "./renderers/econ/MacroModelDiagram";
export { GdpComposition } from "./renderers/econ/GdpComposition";
export { MultiplierRounds } from "./renderers/econ/MultiplierRounds";
export { LaborForce } from "./renderers/econ/LaborForce";
export { PriceIndex } from "./renderers/econ/PriceIndex";
export { DistributionPlot } from "./renderers/stats/DistributionPlot";
export { DiagnosticAccuracy } from "./renderers/clinical/DiagnosticAccuracy";
export { PrevalenceEffect } from "./renderers/clinical/PrevalenceEffect";
export { RocCurve } from "./renderers/clinical/RocCurve";
export { PatientTimeline } from "./renderers/clinical/PatientTimeline";
export { CdsRule } from "./renderers/clinical/CdsRule";
export { QuadrupleAim } from "./renderers/informatics/QuadrupleAim";
export { SociotechnicalModel } from "./renderers/informatics/SociotechnicalModel";
export { Dikw } from "./renderers/informatics/Dikw";
export { WorkflowComparison } from "./renderers/informatics/WorkflowComparison";
export { StandardsMap } from "./renderers/informatics/StandardsMap";
export { HealthItTimeline } from "./renderers/informatics/HealthItTimeline";
export { RunChart } from "./renderers/informatics/RunChart";
export { UsabilityScore } from "./renderers/informatics/UsabilityScore";
export { AdoptionCurve } from "./renderers/informatics/AdoptionCurve";
export { TOOLKITS, isToolEnabled, normalizeToolkitIds } from "./toolkits";
export type { ToolkitId } from "./toolkits";
export { KnowledgeCheck } from "./renderers/KnowledgeCheck";
export { KNOWLEDGE_CHECK_PART_TYPE, collectKnowledgeCheckAnswers, knowledgeCheckAnswerText } from "./knowledgeCheck";
